# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ec9ac26bd2622e244490c7802758b6e30fad49e581d9a1f36542690098dfcd6ebe1555d1df5ea7d1ae58f2aaa085906c25263ba544c3c5909d58ecb9c0d9259

test:
  secret_key_base: 813a2552437c76f20aa9a027011426f68c863f4d7ca56b512e7d4c1597c38795fb95c49e7bd77f8d6c8753def2f497ff7f4b91b0bf28775e1c1e6bc5070c255e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
